### PR TITLE
chore: updated peerDeps to support tailwind 3

### PR DESCRIPTION
**Pull request by kn0wn**

### CODE REVIEW

**Comment by mraichelson** [comment]
Would really appreciate seeing this merged.

**Comment by freekmurze** [comment]
Thanks!

**Comment by awkale** [comment]
has this been published to the npm package?

**Comment by mraichelson** [comment]
I don't think so. I had to install using the repo URL the other day when I was trying it out again as a stopgap solution.

`npm install https://github.com/spatie/tailwind-safelist-generator.git`

**Pull request merged**
